### PR TITLE
!posix/ioctl: handle posix-defined requests

### LINKED ISSUE #1435: `ioctl()` on wrong device returns `EINVAL` instead of appropriate error (`ENOTTY`, `ENOTSOCK`, etc.)
I think [`posix_ioctl()`](https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/master/posix/posix.c#L1718) should handle this by checking the file type against the ioctl request type and if it doesn't match just return error without sending a message. To do so, an additional macro is needed to extract the request type from the ioctl request.

One example of reproduction (ia32-generic-qemu):
```c
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <termios.h>

int main(void)
{
	int fd;
	struct termios t;
	char *name = "testfile";

	fd = creat(name, 0666);

	if (tcgetattr(fd, &t) < 0) {
		perror("tcgetattr");
		return 1;
	}

	unlink(name);
	close(fd);

	return 0;
}
```

Image

### PR DESCRIPTION
**Pull request by julianuziemblo**
Return ENOTTY or ENOTSOCK on file type mismatch
between the open file and the request.

Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1435

This is breaking as SOCK_IOC_TYPE was transferred to kernel and TTY_IOC_TYPE was defined in kernel.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work:
    - https://github.com/phoenix-rtos/libphoenix/pull/468
    - https://github.com/phoenix-rtos/phoenix-rtos-build/pull/273 - *armv8r target doesn't build without this so all tests fail immediatelly* 
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
instead of `Fixes: #1435` you need to provide full `org/repo#issue` stem (as per commit message guidelines), otherwise it won't work (issue is in different repo than the change)

File: posix/posix.c [hunk 1]
```diff
@@ -638,16 +661,38 @@ int posix_open(const char *filename, int oflag, u8 *ustack)
...
+
+				if (posix_getAttr(f->ln, atMode, &attr) < 0) {
+					/* report files that don't report attr as regular files */
+					f->type = ftRegular;
+					break;
+				}
+				else {
+					mode = (mode_t)attr;
+					if (S_ISCHR(mode)) {
+						f->type = ftTty;
```
Comment (ziemleszcz) [inline posix/posix.c:685]: This is an oversimplification. Not all character devices are TTYs.
This breaks `posix_fstat()` and `ioctl_checkPosixDefinedRequests()` for devices that were previously classified as `ftRegular`.

File: posix/posix.c [hunk 2]
```diff
@@ -638,16 +661,38 @@ int posix_open(const char *filename, int oflag, u8 *ustack)
...
+					}
+					else if (S_ISFIFO(mode)) {
+						f->type = ftFifo;
+					}
+					else {
+						f->type = ftRegular;
```
Comment (ziemleszcz) [inline posix/posix.c:691]: File type enums should probably be extended.
At a minimum, add a comment noting that `ftRegular` currently also encompasses internet sockets, block devices, links, and directories.

File: posix/posix.c [hunk 3]
```diff
@@ -638,16 +661,38 @@ int posix_open(const char *filename, int oflag, u8 *ustack)
...
-			else {
-				f->type = ftRegular;
-			}
+			do {
+				if (oid.port == US_PORT) {
+					f->type = ftUnixSocket;
+					break;
+				}
+
+				if (proc_lookup("/dev/posix/pipes", NULL, &srv) >= 0) {
```
Comment (ziemleszcz) [inline posix/posix.c:670]: The commit message says `lookup pipesrv only if we're not US_PORT and handle inet socket server`. Where is the inet socker server part?

Comment (julianuziemblo) [reply posix/posix.c:670]: it was there but it made no sense as socksrv isn't a socket in itself but rather handles ctrl messages (sockmSocket, sockmGetNameInfo, sockmGetAddrInfo, sockmGetIfAddrs). forgot to remove from commit msg, deleted.

File: posix/posix.c (hunk 1 above)
Comment (julianuziemblo) [reply posix/posix.c:685]: yes, but there's no other way for us to differentiate it here. This way at least it works for files that it should work for, e.g. /dev/console

Comment (julianuziemblo) [reply posix/posix.c:690]: I added a comment to the ftRegular enum value. Should I also add a FIXME comment here to somehow differentiate the types in the future, based on some other potential metadata that we don't have now?

Comment (ziemleszcz) [reply posix/posix.c:690]: Please add a TODO comment here.

This line still changes `posix_fstat()` behavior for character devices.
Also, `ioctl_checkPosixDefinedRequests()` accepts TTY ioctls for all character devices.

These issues should be fixed or documented with TODO comments in the relevant functions.

File: posix/posix.c [hunk 4]
```diff
@@ -638,16 +661,41 @@ int posix_open(const char *filename, int oflag, u8 *ustack)
...
+
+				if (posix_getAttr(f->ln, atMode, &attr) < 0) {
+					/* report files that don't report attr as regular files */
+					f->type = ftRegular;
+					break;
+				}
+				else {
+					mode = (mode_t)attr;
+					if (S_ISCHR(mode)) {
+						/* FIXME: for now, we treat every character device as
```
Comment (ziemleszcz) [inline posix/posix.c]: Fix all multi-line comments according to our coding style.

File: posix/posix.c [hunk 5]
```diff
@@ -638,16 +661,41 @@ int posix_open(const char *filename, int oflag, u8 *ustack)
...
+						   a TTY. This behavior should be fixed as it changes
+						   the behavior of e.g. posix_fstat() and ioctl(). */
+						f->type = ftTty;
+					}
+					else if (S_ISFIFO(mode)) {
+						f->type = ftFifo;
+					}
+					else {
+						f->type = ftRegular;
```
Comment (ziemleszcz) [inline posix/posix.c:701]: Add FIXME comment here as well (links, dir etc. are treated as regular files).

**Review by ziemleszcz — APPROVED** [review]
