### PR TITLE
proc/lock: fix owner NULL dereference

### LINKED ISSUE #650: proc/lockSet: null dereference
https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/25c3b9e6400404a15561a6c3aa963ab631c1f0db/proc/threads.c#L1604

Here lock->owner can be NULL, this leads to pagefault inside _proc_threadGetPriority.

It happens relatively often when current and owner are destroyed during lock handling.

### PR DESCRIPTION
**Pull request by etiaro**
## Motivation and Context

Resolves #650 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: riscv64-qemu, ia32-qemu.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

File: proc/threads.c [hunk 1]
```diff
@@ -1596,6 +1596,10 @@ static int _proc_lockSet(lock_t *lock, int interruptible, spinlock_ctx_t *scp)
 		do {
 			/* _proc_lockUnlock will give us a lock by it's own */
 			if (proc_threadWaitEx(&lock->queue, &lock->spinlock, 0, interruptible, scp) == -EINTR) {
+				/* Can happen when thread_destroy is called on lock owner and current */
+				if (lock->owner == NULL) {
+					return -EINTR;
+				}
```
Comment (agkaminski) [inline proc/threads.c:1602]: IMHO the core of the problem is that we clear the `threads_common.spinlock` in line 1594, which can lead to a race on a SMP system.

So I think this check should be performed under `threads_common.spinlock` in the line 1606 instead. Current solution just makes the race less probable

Comment (agkaminski) [reply proc/threads.c:1602]: Eh, I guess the whole `if (lock->owner != current)` should be under spinlock too, I think

**Review by agkaminski — APPROVED** [review]
Perhaps move the condition later and set the priority when `lock->owner != NULL` instead. Personal preference I guess, so just an option to consider.

**Comment by etiaro** [comment]
That's my first though too, but I didn't want to add even more layers of nesting here
